[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
enum_glob_use = "warn"
pedantic = "warn"
nursery = "warn"
unwrap_used = { level = "forbid", priority = 1 }
missing_errors_doc = { level = "allow", priority = 1 }

[workspace.dependencies]
korin = { path = "crates/korin" }
korin_components = { path = "crates/korin_components" }
korin_event = { path = "crates/korin_event" }
korin_geometry = { path = "crates/korin_geometry" }
korin_tree = { path = "crates/korin_tree" }
korin_layout = { path = "crates/korin_layout" }
korin_style = { path = "crates/korin_style" }
korin_reactive = { path = "crates/korin_reactive" }
korin_runtime = { path = "crates/korin_runtime" }
korin_tui = { path = "crates/korin_tui" }
korin_macros = { path = "crates/korin_macros" }
korin_focus = { path = "crates/korin_focus" }
korin_view = { path = "crates/korin_view" }

# member deps
any_spawner = { version = "0.3", default-features = false }
bitflags = "2.10.0"
crossterm = { version = "0.29.0", default-features = false }
convert_case = "0.10.0"
reactive_graph = { version = "0.2.11", features = ["effects"] }
slotmap = "1.0.7"
unicode-width = "0.2"
num-traits = "0.2"

# macro deps
syn = { version = "2", default-features = false }
quote = "1"
proc-macro2 = "1"


# The `calc` feature makes it unsafe for TaffyTree to be `Send + Sync`
taffy = { version = "0.9.2", default-features = false, features = [
  "block_layout",
  "flexbox",
  "grid",
  "content_size",
  "detailed_layout_info",
  "taffy_tree",
  "std",
  "alloc",
] }
thiserror = "2.0.17"
tokio = { version = "1.48.0", default-features = false }
