[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
enum_glob_use = "warn"
pedantic = "warn"
nursery = "warn"
unwrap_used = "warn"

[workspace.dependencies]
korin = { path = "crates/korin" }
korin_document = { path = "crates/korin_document" }
korin_tree = { path = "crates/korin_tree" }
korin_layout = { path = "crates/korin_layout" }
korin_reactive = { path = "crates/korin_reactive" }
korin_focus = { path = "crates/korin_focus" }
korin_render = { path = "crates/korin_render" }

# member deps
bitflags = "2.10.0"
ratatui = "0.29.0"
reactive_graph = "0.2.11"
slotmap = "1.0.7"
taffy = "0.9.2"
thiserror = "2.0.17"
