[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
enum_glob_use = "warn"
pedantic = "warn"
nursery = "warn"
unwrap_used = { level = "forbid", priority = 1 }
missing_errors_doc = { level = "allow", priority = 1 }

[workspace.dependencies]
korin = { path = "crates/korin" }
korin_tree = { path = "crates/korin_tree" }
korin_layout = { path = "crates/korin_layout" }
korin_style = { path = "crates/korin_style" }
korin_reactive = { path = "crates/korin_reactive" }
korin_runtime = { path = "crates/korin_runtime" }
korin_focus = { path = "crates/korin_focus" }
korin_view = { path = "crates/korin_view" }

# member deps
bitflags = "2.10.0"
ratatui = "0.29.0"
reactive_graph = "0.2.11"
slotmap = "1.0.7"

# The `calc` feature makes it unsafe for TaffyTree to be `Send + Sync`
taffy = { version = "0.9.2", default-features = false, features = [
  "block_layout",
  "flexbox",
  "grid",
  "content_size",
  "detailed_layout_info",
  "taffy_tree",
  "std",
  "alloc",
] }
thiserror = "2.0.17"
