[package]
name = "korin_layout"
version.workspace = true
edition.workspace = true

[dependencies]
korin_tree.workspace = true
korin_geometry = { workspace = true, features = ["taffy"] }

taffy.workspace = true
thiserror.workspace = true
unicode-width.workspace = true

[lints]
workspace = true
