[package]
name = "korin_layout"
version.workspace = true
edition.workspace = true

[dependencies]
korin_tree.workspace = true
taffy.workspace = true
thiserror.workspace = true

[lints]
workspace = true
