[package]
name = "korin_view"
version.workspace = true
edition.workspace = true

[dependencies]
korin_event.workspace = true
korin_tree.workspace = true
korin_style.workspace = true
korin_reactive.workspace = true

[lints]
workspace = true
