[package]
name = "korin_macros"
version.workspace = true
edition.workspace = true

[dependencies]
syn = { features = ["full"], workspace = true }
quote.workspace = true
proc-macro2.workspace = true
convert_case.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true
