[package]
name = "dom_events"
version.workspace = true
edition.workspace = true

[dependencies]
bitflags.workspace = true
euclid.workspace = true
keyboard-types.workspace = true

ginyu_force.workspace = true

[lints]
workspace = true
