[package]
name = "korin_core"
version.workspace = true
edition.workspace = true

[dependencies]
korin_layout.workspace = true

bitflags.workspace = true
ratatui-core.workspace = true
ratatui-crossterm.workspace = true
taffy.workspace = true

[lints]
workspace = true
